// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// inprod_mat
NumericMatrix inprod_mat(NumericMatrix X, NumericMatrix B);
RcppExport SEXP msmod_inprod_mat(SEXP XSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    __result = Rcpp::wrap(inprod_mat(X, B));
    return __result;
END_RCPP
}
