# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the inner products of a predictor and coefficient matrix
#'
#' Given a matrix of predictors, X, and matrix of coefficients, B, calculate
#' the inner products, X[i, ] %*%  B[j, ].
#'
#' @param X numeric matrix. Predictors.
#' @param B numeric matrix. Coefficients. 
#' @export
inprod_mat <- function(X, B) {
    .Call('msmod_inprod_mat', PACKAGE = 'msmod', X, B)
}

